USE NETWORK;

INSERT INTO NODE VALUES (1, "Узел 1", "Выборгский район", "Луначарского", "12");
INSERT INTO NODE VALUES (2, "Узел 2", "Выборгский район", "Луначарского", "13");
INSERT INTO NODE VALUES (3, "Узел 3", "Выборгский район", "Луначарского", "14");

INSERT INTO CONNECTOR VALUES (1, "Коннектор 1.1", 4, 1);
INSERT INTO CONNECTOR VALUES (2, "Коннектор 1.2", 2, 1);
INSERT INTO CONNECTOR VALUES (3, "Коннектор 2.1", 6, 2);
INSERT INTO CONNECTOR VALUES (4, "Коннектор 3.1", 2, 3);

INSERT INTO POINT VALUES (1, 1);
INSERT INTO POINT VALUES (1, 3);
INSERT INTO POINT VALUES (1, 4);
INSERT INTO POINT VALUES (2, 2);
INSERT INTO POINT VALUES (3, 1);
INSERT INTO POINT VALUES (3, 3);
INSERT INTO POINT VALUES (3, 4);
INSERT INTO POINT VALUES (3, 5);
INSERT INTO POINT VALUES (4, 1);

INSERT INTO LINK VALUES (1, 1, 2, 2);
INSERT INTO LINK VALUES (1, 3, 3, 1);
INSERT INTO LINK VALUES (1, 4, 3, 3);
INSERT INTO LINK VALUES (3, 4, 4, 1);